title: PCB-Layout
#description: Freelance PCB-Layout
author: Kemal Tokay
logo: static/img/logo.png
email: info@layout-pcb.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.layout-pcb.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: layout-erlangen
#github_username:  jekyll
disqus_shortname: pcb-layout
google_analytics: UA-xxxxxx
share:
  twitter_username: layout-erlangen
  #fb_appid: 000000000000

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
