# Site settings
title: PCB Layout
url: "http://layout-pcb.de"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  Tipps über PCB-Layout in Altium

# Your information
email: info@layout-pcb.de
author: PCB-Layout
avatar: "https://hakandilek.github.io/layout-pcb.de/static/img/logo.png"
profile: Tipps über PCB-Layout in Altium 
twitter_username: Layout_erlangen
#github_username:  github_username

# Comment Service (Disqus)
disqus_shortname: pcb-layout   # get one: https://disqus.com/admin/signup/

permalink: /posts/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->